[package]
name = "axvcpu"
authors = ["aarkegz <aarkegz@gmail.com>"]
version = "0.1.0"
edition = "2024"

[dependencies]
axerrno = "0.1.0"
memory_addr = "0.4"
percpu = "0.2.0"

axaddrspace = "0.1"
axvisor_api = "0.1"
